variables:
  GIT_SSL_NO_VERIFY: "1"

image: docker:latest

stages:
  - build
  - publish

build-empty:
  stage: build
  script:
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build $DOCKER_BUILD_PARAMS --pull -t "${CI_REGISTRY_IMAGE}/empty-debug:$IMAGE_TAG" --file empty-debug.Dockerfile .
    - docker build $DOCKER_BUILD_PARAMS --pull -t "${CI_REGISTRY_IMAGE}/empty:$IMAGE_TAG" --file empty.Dockerfile .

publish:
  stage: publish
  script:
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - echo $IMAGE_TAG
    - docker push "${CI_REGISTRY_IMAGE}/empty-debug:$IMAGE_TAG"
    - docker push "${CI_REGISTRY_IMAGE}/empty:$IMAGE_TAG"
